Decoder skeleton functions
kevv87/OS-Proyecto1 pull request #7
Opened 2022-10-02 00:29 UTC by Cvaztian

Implemented skeleton code for decoder
Missing pixel drawing

2022-10-02 03:09 UTC, kevv87 requested changes

2022-10-02 03:09 UTC, kevv87 commented on decoder/decoder.c
> +struct Descriptor {
Move to types

2022-10-02 03:09 UTC, kevv87 commented on decoder/decoder.c
> +        else { sleep(0.7); }
Por que este sleep?

2022-10-02 03:09 UTC, kevv87 commented on decoder/decoder.c
> +    sleep(3);
Sleep?

2022-10-02 03:09 UTC, kevv87 commented on encoder/encoder.c
> +    printf("%d, %d, %d\n", red, green, blue);
If debug print, remove

2022-10-02 03:09 UTC, kevv87 commented on encoder/encoder.c
> +        printf("%d, %d, %d\n\n\n", img_data->width, img_data->height, img_data->color_channels);
Remove if its a debug print

2022-10-02 03:09 UTC, kevv87 commented on encoder/encoder.c
> +    printf("Encrypted px: %x, Structure index: %d, Px position in file: %d, Insertion time: %s, Is read: %d\n",
remove

2022-10-02 03:30 UTC, Cvaztian commented on encoder/encoder.c
> +    printf("Encrypted px: %x, Structure index: %d, Px position in file: %d, Insertion time: %s, Is read: %d\n",
Mama3.1415chas

2022-10-02 03:30 UTC, Cvaztian commented on encoder/encoder.c
> +        printf("%d, %d, %d\n\n\n", img_data->width, img_data->height, img_data->color_channels);
Mama3.1415chas

2022-10-02 03:30 UTC, Cvaztian commented on encoder/encoder.c
> +    printf("%d, %d, %d\n", red, green, blue);
Mama3.1415chas

2022-10-02 03:30 UTC, Cvaztian commented on decoder/decoder.c
> +    sleep(3);
Mama3.1415chas

2022-10-02 03:30 UTC, Cvaztian commented on decoder/decoder.c
> +        else { sleep(0.7); }
Mama3.1415chas

2022-10-03 02:09 UTC, kevv87 requested changes

2022-10-03 02:09 UTC, kevv87 commented on decoder/decoder.c
> +    /*while(px_counter < decod_cfg.img_size) {
Esto lo borra? O lo dejamos asi?

2022-10-03 02:09 UTC, kevv87 commented on encoder/encoder.c
> +        printf("%d, %d, %d\n\n\n", img_data->width, img_data->height, img_data->color_channels);
xD Lo quitamos o que?

2022-10-03 05:38 UTC, kevv87 approved these changes

2022-10-03 05:38 UTC, merged